apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gotify-certificate
  namespace: gotify
spec:
  # Secret names are always required.
  secretName: gotify-cert
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - gotify.wheelerlab.dev
