apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: navidrome-certificate
  namespace: navidrome # Assuming the namespace will be navidrome
spec:
  # Secret names are always required.
  secretName: navidrome-cert
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - tunes.wheelerlab.dev
