{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "navidrome.fullname" . }}
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.hosts.host }}`)
      kind: Rule
      services:
        - name: {{ include "navidrome.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
