apiVersion: v1
kind: Service
metadata:
  name: proxmox-external
  namespace: default # Or the namespace where you want this service to reside
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8006 # Proxmox default HTTPS port
      targetPort: 8006
