apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxmox-cert
  namespace: default # Must match the IngressRoute's namespace
spec:
  secretName: proxmox-cert
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - proxmox.wheelerlab.dev
