replicaCount: 1

image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: bw.wheelerlab.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: vaultwarden-cert-secret
     hosts:
       - bw.wheelerlab.dev

persistence:
  enabled: true
  size: 1Gi
  storageClassName: "longhorn-retain"
  accessMode: ReadWriteMany
  mountPath: /data

env:
  # This Token will be overwritten by the one in the secrets.yaml
  ADMIN_TOKEN: ""
