# HDD NFS SHARE for bulk media storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-slow-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 28T
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # Allows multiple pods to read/write
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.42.3
    path: "/mnt/user/NetworkStorage"
