apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  namespace: default
spec:
  volumes:
    - name: nfs-fast-pvc-storage
      persistentVolumeClaim:
        claimName: nfs-fast-pvc
    - name: nfs-slow-pvc-storage
      persistentVolumeClaim:
        claimName: nfs-slow-pvc
  containers:
    - name: nfs-test-container
      image: busybox:1.36
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - name: nfs-fast-pvc-storage
          mountPath: "/mnt/nfs-fast-data"
        - name: nfs-slow-pvc-storage
          mountPath: "/mnt/nfs-slow-data"
