ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik-dashboard.wheelerlab.dev`)
    entryPoints:
      - websecure
    tls:
      secretName: traefik-dashboard-cert-secret
providers:
  kubernetesGateway:
    enabled: true
gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
additionalArguments:
  - "--entrypoints.websecure.proxyProtocol.trustedIPs=10.42.0.0/16,10.43.0.0/16,100.64.0.0/16"
  - "--entrypoints.websecure.forwardedHeaders.trustedIPs=10.42.0.0/16,10.43.0.0/16,100.64.0.0/16"
  - "--accesslog=true"
  - "--accesslog.filepath=/dev/stdout"
  - "--accesslog.format=json"