apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingressroute
  namespace: immich
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.wheelerlab.dev`)
      kind: Rule
      services:
        - name: immich-server
          port: 2283
  tls:
    secretName: immich-cert
