apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-cert
  namespace: immich
spec:
  secretName: immich-cert
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - immich.wheelerlab.dev
