apiVersion: v1
kind: Secret
metadata:
  name: {{ include "book-keeper.fullname" . }}
  labels:
    {{- include "book-keeper.labels" . | nindent 4 }}
type: Opaque
data:
  BOT_TOKEN: {{ .Values.secrets.BOT_TOKEN | b64enc | quote }}
  AUTH_TOKEN: {{ .Values.secrets.AUTH_TOKEN | b64enc | quote }}
